version: "3"

services:
    deephack:
        build: ./web
        ports: ["8080:8080"]
        depends_on:
            - db
        volumes:
            - ./web:/usr/src/app

    #mongo-seed:
        #build: ./mongo-seed
        #links:
            #- db

    db:
        image: mongo:3.5
        ports: ['27018:27017']

